apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - promtail.yaml
  - ../../base/loki

# Common logging configurations
configMapGenerator:
  - name: promtail-config
    files:
      - promtail-config.yaml

# Common labels for all logging resources
commonLabels:
  app.kubernetes.io/part-of: logging

# Resource defaults for logging components
patches:
  - target:
      kind: DaemonSet
      name: promtail
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
