# Service Account for ARS applications
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ars-service-account
  namespace: ars
  labels:
    app.kubernetes.io/name: ars
---
# Role with necessary permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ars-role
  namespace: ars
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ars-role-binding
  namespace: ars
subjects:
- kind: ServiceAccount
  name: ars-service-account
  namespace: ars
roleRef:
  kind: Role
  name: ars-role
  apiGroup: rbac.authorization.k8s.io
---
# Pod Security Standards
# The pod security labels will be added to the namespace in the namespace.yaml file
