apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-deployment.yaml
  - grafana-datasources.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: grafana
      app.kubernetes.io/managed-by: kustomize 