apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources
resources:
  - ../../base

# Development-specific name suffix
nameSuffix: -dev

# Development-specific labels and annotations
labels:
  - includeSelectors: true
    pairs:
      environment: development
      tier: development

# Development-specific patches
patches:
  # Patch Prometheus for development
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"

  # Patch Grafana for development
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"

# Development-specific configurations
configMapGenerator:
  - name: infrastructure-config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - FEATURE_FLAG_DEV_MODE=true

# Development-specific secret overrides
secretGenerator:
  - name: infrastructure-secrets
    behavior: merge
    literals:
      - DB_PASSWORD=dev-password
      - API_KEY=dev-api-key
