auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Increase the reject_old_max_age to accept older logs
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 24h  # 1 day
  max_streams_per_user: 10000
  max_global_streams_per_user: 10000
  max_line_size: 1048576  # 1MB
  max_line_size_truncate: false
  max_query_length: 721h  # 30 days
  max_query_parallelism: 32
  max_query_series: 5000
  max_cache_freshness_per_query: 10m
  max_entries_limit_per_query: 5000
  max_concurrent_tail_requests: 20
