server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 20
    batchwait: 1s
    batchsize: 1048576
    timeout: 10s
    external_labels:
      host: docker-host
      job: docker-logs

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      # Only process logs from running containers
      - source_labels: [__meta_docker_container_state_running]
        regex: true
        action: keep
      # Add container metadata as labels
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_image]
        target_label: image
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project
      - source_labels: [__meta_docker_container_label_com_docker_compose_config_hash]
        target_label: compose_config_hash
      - source_labels: [__meta_docker_container_label_com_docker_compose_container_number]
        target_label: compose_container_number
      - source_labels: [__meta_docker_container_label_com_docker_compose_version]
        target_label: compose_version
      # Ensure we always have at least one label
      - target_label: job
        replacement: docker-logs
      - target_label: host
        replacement: docker-host
    pipeline_stages:
      - docker: {}
      - timestamp:
          source: time
          format: RFC3339Nano
      # Drop logs older than 1 hour
      - drop:
          older_than: 1h
          drop_counter_reason: log_too_old
      - output:
          source: log