global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
  # Add more scrape configs as needed
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']