apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: ars
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
      annotations:
        container.apparmor.security.beta.kubernetes.io/falco: unconfined
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        imagePullPolicy: Always
        env:
        - name: FALCO_DRIVER
          value: "userspace"
        - name: FALCO_DRIVER_LOADER
          value: "disabled"
        - name: FALCO_DRIVER_LOADER_OPTS
          value: "--userspace"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: falco-config
          mountPath: /etc/falco/falco.yaml
          subPath: falco.yaml
        - name: falco-rules
          mountPath: /etc/falco/falco_rules.yaml
          subPath: falco_rules.yaml
      volumes:
      - name: falco-config
        configMap:
          name: falco-config
      - name: falco-rules
        configMap:
          name: falco-rules
