apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: ars
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
      annotations:
        container.apparmor.security.beta.kubernetes.io/falco: unconfined
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_PTRACE
              - SYS_ADMIN
              - SYSLOG
        volumeMounts:
        - name: falco-config
          mountPath: /etc/falco/falco.yaml
          subPath: falco.yaml
        - name: falco-rules
          mountPath: /etc/falco/falco_rules.yaml
          subPath: falco_rules.yaml
        - name: dev-fs
          mountPath: /host/dev
          readOnly: true
        - name: proc-fs
          mountPath: /host/proc
          readOnly: true
        - name: boot-fs
          mountPath: /host/boot
          readOnly: true
        - name: lib-modules
          mountPath: /host/lib/modules
          readOnly: true
        - name: usr-src
          mountPath: /host/usr/src
          readOnly: true
        - name: falco-bpf
          mountPath: /root/.falco
      volumes:
      - name: falco-config
        configMap:
          name: falco-config
      - name: falco-rules
        configMap:
          name: falco-rules
      - name: dev-fs
        hostPath:
          path: /dev
      - name: proc-fs
        hostPath:
          path: /proc
      - name: boot-fs
        hostPath:
          path: /boot
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: falco-bpf
        emptyDir: {}
