apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - namespace.yaml
  - falco-daemonset.yaml
  - falco-sidekick-deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: security
      app.kubernetes.io/managed-by: kustomize

images:
  - name: falcosecurity/falco
    newTag: latest
  - name: falcosecurity/falcosidekick
    newTag: latest
