apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ars

resources:
  - falco-config.yaml
  - falco-daemonset.yaml
  - falco-sidekick-deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: security
      app.kubernetes.io/managed-by: kustomize

images:
  - name: falcosecurity/falco
    newTag: latest
  - name: falcosecurity/falcosidekick
    newTag: 2.30.0

configMapGenerator:
  - name: falco-rules
    files:
      - falco_rules.yaml=falco_rules.yaml
    options:
      disableNameSuffixHash: true
