apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Production-specific name suffix
nameSuffix: -prod

# Production-specific labels and annotations
labels:
  - includeSelectors: true
    pairs:
      environment: production
      tier: production

# Production-specific patches
patchesStrategicMerge:
  - namespace-patch.yaml
  # Add other prod-specific patches here

# Production-specific configurations
configMapGenerator:
  - name: infrastructure-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info

# Production-specific secret overrides
secretGenerator:
  - name: infrastructure-secrets
    behavior: merge
    literals:
      - DB_PASSWORD=change-me-in-production
      - API_KEY=change-me-in-production

# Production-specific replicas
replicas:
  - name: ars-frontend
    count: 3
  - name: ars-backend
    count: 3

# Production resource limits and requests
patches:
  - target:
      kind: Deployment
      name: ars-*
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
