apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ars-prod

resources:
  - ../../base

patchesStrategicMerge:
  - namespace-patch.yaml
  # Add other prod-specific patches here

nameSuffix: -prod

# Production-specific configurations
commonLabels:
  environment: production

# Production-specific resources
resources:
  - ../../infra/monitoring/prod
  - ../../infra/logging/prod

# Production-specific configurations
configMapGenerator:
  - name: ars-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info

# Production-specific replicas
replicas:
  - name: ars-frontend
    count: 3
  - name: ars-backend
    count: 3

# Production resource limits and requests
patches:
  - target:
      kind: Deployment
      name: ars-*
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
