apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrapeconfigs
  namespace: ars
data:
  additional-scrape-configs.yaml: |
    scrape_configs:
      - job_name: 'nginx-exporter'
        static_configs:
          - targets: ['nginx-exporter:9113']
