apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources from infrastructure
resources:
  - ../../base
  - ../../monitoring
  - ../../logging
  - ../../storage
  - ../../security
  - ../../networking

# Development-specific configurations
namespace: ars-dev

# Common labels for all resources in dev
commonLabels:
  environment: dev
  tier: development

# Development-specific patches
patches:
  # Patch Prometheus for development
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"

  # Patch Grafana for development
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"

  # Patch MinIO for development
  - target:
      kind: Deployment
      name: minio
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"

# Development-specific environment variables
configMapGenerator:
  - name: infrastructure-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug

# Development-specific secrets (in a real environment, use sealed-secrets or similar)
secretGenerator:
  - name: infrastructure-secrets
    behavior: merge
    literals:
      - DB_PASSWORD=dev-password
      - API_KEY=dev-api-key-123
