apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - node-exporter-daemonset.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: node-exporter
      app.kubernetes.io/managed-by: kustomize 