apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base resources
resources:
  - storage/storage-classes.yaml
  - networking/network-policies.yaml
  - security/rbac.yaml

# Common configurations
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: kustomize
      environment: base

# Common annotations for all resources
commonAnnotations:
  description: "Base infrastructure configuration"
  kustomize.toolkit.fluxcd.io/checksum: 5a9f9d6c13d11609bdf5d6a7d15c1f9f2e4eb4bd5b8f0755ac56961f61335859

# Name prefix for all resources
namePrefix: ars-

# Name suffix for all resources
nameSuffix: ""

# Add common environment variables to all resources
configMapGenerator:
  - name: infrastructure-config
    literals:
      - ENVIRONMENT=base
      - LOG_LEVEL=info

# Add common secret environment variables
secretGenerator:
  - name: infrastructure-secrets
    type: Opaque
    literals:
      - DB_PASSWORD=change-me
      - API_KEY=change-me
