services:
  awx:
    image: quay.io/ansible/awx:21.14.0
    container_name: awx
    ports:
      - "8043:8043"
    environment:
      - SECRET_KEY=awxsecretkey
      - AWX_ADMIN_USER=admin
      - AWX_ADMIN_PASSWORD=password
    volumes:
      - awx-data:/var/lib/awx

  oceanhealing:
    build:
      context: ../OceanHealing
      dockerfile: Dockerfile
    container_name: oceanhealing
    ports:
      - "5543:5543"
    env_file:
      - ../OceanHealing/.env
    restart: unless-stopped

volumes:
  awx-data:
