apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-dev

resources:
  - ../../base/monitoring

# Development-specific monitoring configurations
configMapGenerator:
  - name: prometheus-config
    behavior: merge
    files:
      - prometheus.yml

patches:
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
