apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oceanhealing-dev-deployment.yaml
  - oceanhealing-service.yaml
  - otel-config.yaml

configMapGenerator:
  - name: promtail-sidecar-config
    files:
      - promtail.yaml=promtail-sidecar.yaml
