apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanhealing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oceanhealing
  template:
    metadata:
      labels:
        app: oceanhealing
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: oceanhealing
          image: ghcr.io/webdevs-net/oceanhealing:latest
          ports:
            - containerPort: 5543
          readinessProbe:
            httpGet:
              path: /health
              port: 5543
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: oceanhealing
spec:
  selector:
    app: oceanhealing
  ports:
    - protocol: TCP
      port: 5543
      targetPort: 5543
  type: ClusterIP
