apiVersion: v1
kind: Service
metadata:
  name: oceanhealing-dev
  namespace: ars
  labels:
    app: oceanhealing
    environment: development
    tier: development
spec:
  selector:
    app: oceanhealing
    environment: development
    tier: development
  ports:
    - name: http
      port: 5543
      targetPort: 5543
      protocol: TCP
  type: ClusterIP 