apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehive-data
  namespace: ars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thehive
  namespace: ars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thehive
  template:
    metadata:
      labels:
        app: thehive
    spec:
      containers:
      - name: thehive
        image: strangebee/thehive:5.2
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: thehive-data
          mountPath: /data
      volumes:
      - name: thehive-data
        persistentVolumeClaim:
          claimName: thehive-data
---
apiVersion: v1
kind: Service
metadata:
  name: thehive
  namespace: ars
spec:
  selector:
    app: thehive
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
