apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - loki-config.yaml
  - loki-deployment.yaml
  - promtail-config.yaml
  - promtail-daemonset.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: logging
      app.kubernetes.io/managed-by: kustomize

images:
  - name: grafana/loki
    newTag: 2.8.0
  - name: grafana/promtail
    newTag: 2.8.0
