apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/log/containers/*.log
    
    pipeline_stages:
    - docker: {}
    - match:
        selector: '{job!="kube-proxy"}'
        stages:
        - json:
            expressions:
              stream: stream
              log: log
        - labels:
            stream:
        - output:
            source: log
    
    - match:
        selector: '{job=~"kube-proxy"}'
        stages:
        - regex:
            expression: '(?P<log>.*)'
        - labels:
            log: log
