apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../components/monitoring
  - ../components/grafana
  - ../components/kube-state-metrics
  - ../components/node-exporter
  - ../components/loki
  - ../components/tempo

patches:
  - target:
      kind: Service
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30909
  - target:
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30300

images:
  - name: prom/prometheus
    newName: prom/prometheus
    newTag: latest
  - name: grafana/grafana
    newName: grafana/grafana
    newTag: latest
