apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-pvc.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/managed-by: kustomize

images:
  - name: prom/prometheus
    newTag: latest
  - name: grafana/grafana
    newTag: latest
