apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus-pv.yaml
  - prometheus-rbac.yaml
  - prometheus-pvc.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

patches:
  - target:
      kind: Service
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30909
  - target:
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30300

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize

images:
  - name: prom/prometheus
    newName: prom/prometheus
    newTag: latest
  - name: grafana/grafana
    newName: grafana/grafana
    newTag: latest
