apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging-dev

resources:
  - ../../base/logging

# Development logging configurations
configMapGenerator:
  - name: loki-config
    behavior: merge
    files:
      - loki-config.yaml
  - name: promtail-config
    behavior: merge
    files:
      - promtail-config.yaml

# Scale down for development
patches:
  - target:
      kind: StatefulSet
      name: loki
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
