apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus
  - alertmanager
  - grafana
  - kube-state-metrics
  - node-exporter

# Common monitoring configurations
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml

# Common labels for all monitoring resources
commonLabels:
  app.kubernetes.io/part-of: monitoring

# Resource defaults for monitoring components
patches:
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi

  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
