apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all resources
resources:
  - namespace.yaml
  - base
  - monitoring

# Common configurations
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: kustomize
      environment: base
