---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: ars
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app.kubernetes.io/name: storage
    app.kubernetes.io/part-of: ars
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/name: security
    app.kubernetes.io/part-of: ars
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: ars
  labels:
    app.kubernetes.io/name: ars
    app.kubernetes.io/part-of: ars
    environment: base
    # Pod Security Standards - changed to privileged to allow Falco
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    app.kubernetes.io/name: networking
    app.kubernetes.io/part-of: ars
    environment: base
