apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize

images:
  - name: prom/prometheus
    newTag: latest
  - name: grafana/grafana
    newTag: latest
