---
- name: Deploy ARS Lab Kubernetes Stack
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kube_namespace: ars
    infrastructure_path: "{{ playbook_dir }}/../infrastructure"
  tasks:
    - name: Ensure ars namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ kube_namespace }}"
        state: present

    - name: Deploy ARS Lab Infrastructure with Kustomize
      kubernetes.core.k8s:
        state: present
        src: "{{ infrastructure_path }}"
        apply: true
