apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/config.yaml
  - database/statefulset.yaml
  - redis/statefulset.yaml
  - backend/deployment.yaml
  - frontend/deployment.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: ars
  app.kubernetes.io/managed-by: kustomize

# Name prefix for all resources
namePrefix: ars-

# Namespace for all resources
namespace: ars

# Add configMapGenerator for environment-specific configurations
configMapGenerator:
  - name: ars-environment
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info

# Add secretGenerator for sensitive data (in production, use external secret management)
secretGenerator:
  - name: ars-secrets
    behavior: merge
    literals:
      - JWT_SECRET=change-me-in-production
      - SESSION_SECRET=change-me-in-production

# Add patches for environment-specific configurations
patches:
  - path: patches/environment-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: ars-*
