apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: ars
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  type: ClusterIP 