apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-new
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/grafana-data"
  persistentVolumeReclaimPolicy: Retain 