apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-new
  labels:
    type: local
    app: prometheus
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/prometheus-data"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem 